version: '3'

networks:
  laravel:

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - laravel

  php:
    image: lovdianchel/laravel-vue:0.1
    container_name: php
    depends_on:
      - mysql
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    networks:
      - laravel
